# Railway deployment configuration with FFmpeg support
# Based on: https://railway.app/help/fix-ffmpeg-issues

[phases.setup]
nixPkgs = ['ffmpeg', 'nodejs_22']

[phases.build]
cmds = ['npm ci --no-cache --prefer-offline', 'npm run build']

[start]
cmd = 'npm start'

[env]
NODE_ENV = 'production'
RAILWAY_ENVIRONMENT = 'production'

# Disable problematic cache mounts
[variables]
NIXPACKS_NO_CACHE = '1'
